FROM STUDENT S
WHERE S.SNO IN
     (SELECT SNO FROM SC WHERE CNO='1')
上面的HQL语句在HIBERNATE后台生成的SQL语句为：
    SELECT
           STUDENT0_.ID AS ID1_,
           STUDENT0_.SNO AS SNO1_,
           STUDENT0_.SNAME AS SNAME1_,
          STUDENT0_.SSEX AS SSEX1_,
          STUDENT0_.SDEPT AS SDEPT1_,
          STUDENT0_.SAGE AS SAGE1_,
          STUDENT0_.SADDRESS AS SADDRESS1_
    FROM
        JOBLOG.STUDENT STUDENT0_
    WHERE
        STUDENT0_.SNO IN (
  SELECT
       SC1_.SNO
  FROM
       JOBLOG.SC SC1_
  WHERE
       SC1_.CNO='1'
        )
