DROP TABLE EJB_IHT_SingleTable_Biology;
CREATE TABLE EJB_IHT_SingleTable_Biology(
  DISCRIMINATOR VARCHAR2(30 CHAR) NOT NULL,
  BLG_ID NUMBER(10, 0) NOT NULL,
  BLG_SPEED NUMBER(5, 0),
  PLT_CHLOROPHYL VARCHAR2(30 CHAR),
  WMLN_COLOR VARCHAR2(30 CHAR)
, PRIMARY KEY ( BLG_ID )
, CONSTRAINT Crt_Biology_Type CHECK (DISCRIMINATOR IN ('Biology','Plant','Watermelon'))
);
