DROP TABLE EJB_IHT_TablePerClass_Vehicle;
DROP TABLE EJB_IHT_TablePerClass_Car;
DROP TABLE EJB_IHT_TablePerClass_Camion;
CREATE TABLE EJB_IHT_TablePerClass_Vehicle(
  VH_ID NUMBER(*, 0) NOT NULL,
  VH_SPEED NUMBER(5, 0)
, PRIMARY KEY ( VH_ID )
);
CREATE TABLE EJB_IHT_TablePerClass_Car
(
  VH_ID NUMBER(*, 0) NOT NULL,
  VH_SPEED NUMBER(5, 0),
  CARD_SPEED VARCHAR2(30 CHAR)
, PRIMARY KEY(VH_ID)
);
CREATE TABLE EJB_IHT_TablePerClass_Camion(
  VH_ID NUMBER(*, 0) NOT NULL,
  VH_SPEED NUMBER(5, 0),
  CARD_SPEED VARCHAR2(30 CHAR),
  CAMION_CONTAINER VARCHAR2(30 CHAR)
, PRIMARY KEY ( VH_ID)
);
