DROP TABLE EJB_RELATION_OTO_IdCard cascade constraint;
DROP TABLE EJB_RELATION_OTO_Person  cascade constraint;
CREATE TABLE EJB_RELATION_OTO_IdCard(
  CARD_ID NUMBER(10, 0) NOT NULL,
  CARDNO VARCHAR2(18 CHAR) NOT NULL,
  CARD_PERSON_ID NUMBER(10, 0) NOT NULL
, PRIMARY KEY (  CARD_ID  )
, UNIQUE ( CARDNO) ENABLE
, UNIQUE(  CARD_PERSON_ID) ENABLE    
);
CREATE TABLE EJB_RELATION_OTO_PERSON
(
  PERSON_ID NUMBER(10, 0) NOT NULL,
  PERSON_NAME VARCHAR2(32 CHAR) NOT NULL,
  ENUM_SEX VARCHAR2(255 CHAR) NOT NULL,
  AGE NUMBER(5, 0),
  BIRTHDAY DATE,
  CARD_ID NUMBER(10, 0) NOT NULL
, PRIMARY KEY ( PERSON_ID )
, UNIQUE(  CARD_ID) ENABLE
);
ALTER TABLE EJB_RELATION_OTO_IdCard ADD CONSTRAINT IdCard_FK_Person_ID
  FOREIGN KEY(  CARD_PERSON_ID) REFERENCES EJB_RELATION_OTO_PERSON(PERSON_ID) ENABLE;
ALTER TABLE EJB_RELATION_OTO_PERSON ADD CONSTRAINT Person_FK_Card_ID
  FOREIGN KEY(  CARD_ID) REFERENCES EJB_RELATION_OTO_IdCard(CARD_ID) ENABLE;