DROP TABLE EJB_Relation_OTM_Order;
DROP TABLE EJB_Relation_OTM_OrderItem;
CREATE TABLE EJB_Relation_OTM_Order
(
  ORDER_ID NUMBER(10, 0) NOT NULL,
  AMOUNT FLOAT(126),
  CREATE_DATE TIMESTAMP(6)
, PRIMARY KEY(ORDER_ID)
);
CREATE TABLE EJB_Relation_OTM_OrderItem
(
  Order_Item_ID NUMBER(10, 0) NOT NULL,
  PRODUCTNAME VARCHAR2(255 CHAR),
  PRICE FLOAT(126),
  ORDER_ID NUMBER(10, 0) NOT NULL
, PRIMARY KEY( ID  )
, FOREIGN KEY( ORDER_ID) REFERENCES EJB_OneToMany_Order(ORDER_ID) ENABLE
);
