DROP TABLE EJB_IHT_JOINED_COMMODITY;
DROP TABLE EJB_IHT_JOINED_HOME_APPLIANCE;
DROP TABLE EJB_IHT_JOINED_WASHER;

CREATE TABLE EJB_IHT_JOINED_COMMODITY (
  COMMODITY_ID NUMBER(10, 0) NOT NULL,
  COMMODITY_NAME VARCHAR2(255 CHAR) NOT NULL
, PRIMARY KEY(COMMODITY_ID  )
);
CREATE TABLE EJB_IHT_JOINED_HOME_APPLIANCE
(
  FK_COMMODITY_ID NUMBER(10, 0) NOT NULL,
  PRICE NUMBER(19, 2)
, PRIMARY KEY (FK_COMMODITY_ID )
, FOREIGN KEY ( FK_COMMODITY_ID) REFERENCES EJB_IHT_JOINED_COMMODITY(COMMODITY_ID) ENABLE
);
CREATE TABLE EJB_IHT_JOINED_WASHER
(
  FK_COMMODITY_ID NUMBER(*, 0) NOT NULL,
  CONTAINER VARCHAR2(30 CHAR)
, PRIMARY KEY(FK_COMMODITY_ID)
, FOREIGN KEY ( FK_COMMODITY_ID) REFERENCES EJB_IHT_JOINED_HOME_APPLIANCE(FK_COMMODITY_ID) ENABLE
);